apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keycloakclientregistrations.k8s.kiwigrid.com
spec:
  group: k8s.kiwigrid.com
  version: v1beta1
  scope: Cluster
  names:
    plural: keycloakclientregistrations
    singular: keycloakclientregistration
    kind: KeycloakClientRegistration
    shortNames:
      - kcr
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            clientId:
              type: string
            publicClient:
              type: boolean
            redirectUris:
              items:
                type: string
              type: array
            webOrigins:
              items:
                type: string
              type: array
          required:
            - clientId
            - redirectUris
            - webOrigins
          type: object
        status:
          type: object
