apiVersion: k8s.kiwigrid.com/v1beta1
kind: KeycloakClient
metadata:
  name: pizza-service
spec:
  keycloak: fully-configured-keycloak
  realm: food-realm
  clientId: pizza-service
  clientType: confidential
  defaultClientScopes:
  - email
  - profile
  - roles
  directAccessGrantsEnabled: true
  standardFlowEnabled: false
  implicitFlowEnabled: false
  serviceAccountsEnabled: true
  secretName: pizza-service
  roles:
    - name: service
      realmRoles:
        - service
        - admin
        - grandmaster
  serviceAccountRealmRoles:
    - editor
  mapper:
    - name: audience
      protocolMapper: oidc-audience-mapper
      config:
        claim.name: audience
        access.token.claim: "true"
        included.client.audience: pizza-service
    - name: tenant
      protocolMapper: oidc-script-based-protocol-mapper
      config:
        claim.name: tenant
        access.token.claim: "true"
        jsonType.label: String
        script: "realm.getName();"
    - name: username
      protocolMapper: oidc-usermodel-property-mapper
      config:
        claim.name: username
        access.token.claim: "true"
        jsonType.label: String
        user.attribute: username
    - name: roles
      protocolMapper: oidc-usermodel-client-role-mapper
      config:
        claim.name: roles
        access.token.claim: "true"
        jsonType.label: String
        multivalued: "true"
        usermodel.clientRoleMapping.clientId: pizza-service
        usermodel.clientRoleMapping.rolePrefix: pizza-service-