apiVersion: k8s.kiwigrid.com/v1beta1
kind: KeycloakClientScope
metadata:
  name: fully-configured-clientscope
spec:
  keycloak: fully-configured-keycloak
  realm: fully-configured-realm
  name: fully-configured-clientscope
  mapper:
    - name: scope-group-mapper-example
      protocolMapper: oidc-script-based-protocol-mapper
      config:
        claim.name: tenant
        access.token.claim: "true"
        jsonType.label: String
        script: |-
          realm.getName();